"""Grafix が利用する pyimgui 2 pyglet renderer の型定義。"""

from typing import Any


class PygletProgrammablePipelineRenderer:
    def __init__(self, window: Any, attach_callbacks: bool = ...) -> None: ...
    def process_inputs(self) -> None: ...
    def render(self, draw_data: Any) -> None: ...
    def refresh_font_texture(self) -> None: ...
    def shutdown(self) -> None: ...
