# This file is auto-generated by grafix.devtools.generate_stub. DO NOT EDIT.
# Regenerate with: python -m grafix stub

# ruff: noqa: F401, E402

from __future__ import annotations

from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any, Literal, Protocol, TypeAlias

from grafix.core.geometry import Geometry
from grafix.core.layer import Layer
from grafix.core.scene import SceneItem

Vec3: TypeAlias = tuple[float, float, float]

class _G(Protocol):
    def __call__(self, name: str | None = None) -> _G:
        """ラベル付き primitive 名前空間を返す。"""
        ...
    def arc(self, *, activate: bool = ..., radius: float = ..., start: float = ..., sweep: float = ..., segments: int = ..., center: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        開始角とsigned sweepから開いた円弧を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            radius: 円弧の中心から輪郭までの半径を指定します。, float, range [0.0, 200.0]
            start: +X 軸を基準とする円弧の開始角を度単位で指定します。, float, range [-360.0, 360.0]
            sweep: 開始角から終点までの符号付き回転量を度単位で指定します。, float, range [-360.0, 360.0]
            segments: 円弧を近似する直線セグメントの数を指定します。, int, range [1, 512]
            center: 円弧の中心となる XYZ 座標を指定します。, vec3, range [-300.0, 300.0]
        """
        ...
    def asemic(self, *, activate: bool = ..., text: str = ..., seed: int = ..., n_nodes: int = ..., candidates: int = ..., stroke_min: int = ..., stroke_max: int = ..., walk_min_steps: int = ..., walk_max_steps: int = ..., stroke_style: Literal['line', 'bezier'] = ..., bezier_samples: int = ..., bezier_tension: float = ..., text_align: Literal['left', 'center', 'right'] = ..., glyph_advance_em: float = ..., space_advance_em: float = ..., letter_spacing_em: float = ..., line_height: float = ..., use_bounding_box: bool = ..., box_width: float = ..., box_height: float = ..., show_bounding_box: bool = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        擬似文字（asemic）の文章をポリライン列として生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            text: 描画する文字列
            seed: 全体 seed
            n_nodes: ノード数（少なすぎるとストロークが生成できないことがある）
            candidates: best-candidate の候補数（大きいほど均一になりやすい）
            stroke_min: ストローク本数の最小値
            stroke_max: ストローク本数の最大値
            walk_min_steps: ランダムウォークの最小ステップ数
            walk_max_steps: ランダムウォークの最大ステップ数
            stroke_style: ストロークの描画スタイル
            bezier_samples: `"bezier"` 時の 1 セグメントあたりのサンプル点数（2 以上）
            bezier_tension: `"bezier"` 時の張り（0=曲がりやすい, 1=直線寄り）
            text_align: 行揃え
            glyph_advance_em: 空白以外の文字送り（em）
            space_advance_em: 空白の文字送り（em）
            letter_spacing_em: 追加の文字間スペーシング（em）
            line_height: 行送り（em）
            use_bounding_box: True のとき `box_width` による自動改行と、`show_bounding_box` による枠描画を有効にする
            box_width: 幅による自動改行を行う際のボックス幅（出力座標系）
            box_height: デバッグ用ボックス表示の高さ（出力座標系）
            show_bounding_box: True のとき、`box_width/box_height` で指定されたボックス枠（4本の線分）を追加で描画する
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率
        """
        ...
    def bezier(self, *, activate: bool = ..., p0: Sequence[float] = ..., p1: Sequence[float] = ..., p2: Sequence[float] = ..., p3: Sequence[float] = ..., segments: int = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        4制御点からcubic Bezier curveを生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            segments: 4 制御点で定まる曲線を近似する直線セグメントの数を指定します。, int, range [1, 512]
        """
        ...
    def circle(self, *, activate: bool = ..., radius: float = ..., segments: int = ..., center: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        円を閉じたpolylineとして生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            radius: 半径
            segments: 周上の線分数
            center: 円の中心
        """
        ...
    def ellipse(self, *, activate: bool = ..., radius_x: float = ..., radius_y: float = ..., angle: float = ..., segments: int = ..., center: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        楕円を閉じたpolylineとして生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            radius_x: 回転前の X 軸方向における楕円の半径を指定します。, float, range [0.0, 200.0]
            radius_y: 回転前の Y 軸方向における楕円の半径を指定します。, float, range [0.0, 200.0]
            angle: 楕円を中心まわりに回転させる角度を度単位で指定します。, float, range [-180.0, 180.0]
            segments: 楕円周を近似する直線セグメントの数を指定します。, int, range [3, 512]
            center: 楕円の中心となる XYZ 座標を指定します。, vec3, range [-300.0, 300.0]
        """
        ...
    def grid(self, *, activate: bool = ..., nx: int = ..., ny: int = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        グリッド（縦線 nx 本 + 横線 ny 本）を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            nx: 縦線の本数
            ny: 横線の本数
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...
    def laplace_field_grid(self, *, activate: bool = ..., preset: Literal['cylinder_uniform', 'mobius', 'exp'] = ..., u_min: float = ..., u_max: float = ..., v_min: float = ..., v_max: float = ..., n_u: int = ..., n_v: int = ..., samples: int = ..., center: Vec3 = ..., scale: float = ..., rotate: float = ..., clip: bool = ..., clip_xmin: float = ..., clip_xmax: float = ..., clip_ymin: float = ..., clip_ymax: float = ..., a: float = ..., U: float = ..., gap: float = ..., draw_boundary: bool = ..., boundary_samples: int = ..., alpha_re: float = ..., alpha_im: float = ..., beta_re: float = ..., beta_im: float = ..., gamma_re: float = ..., gamma_im: float = ..., delta_re: float = ..., delta_im: float = ..., k_re: float = ..., k_im: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        共形写像ベースの直交格子（等ポテンシャル線/流線風）を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            preset: `"cylinder_uniform" | "mobius" | "exp"`
            u_min: 写像元 W=u+iv 平面で描画する u 座標の下限を指定します。, float, range [-10.0, 10.0]
            u_max: 写像元 W=u+iv 平面で描画する u 座標の上限を指定します。, float, range [-10.0, 10.0]
            v_min: 写像元 W=u+iv 平面で描画する v 座標の下限を指定します。, float, range [-10.0, 10.0]
            v_max: 写像元 W=u+iv 平面で描画する v 座標の上限を指定します。, float, range [-10.0, 10.0]
            n_u: u を固定して v 方向へたどる格子線の本数を指定します。, int, range [0, 200]
            n_v: v を固定して u 方向へたどる格子線の本数を指定します。, int, range [0, 200]
            samples: 1 本あたりのサンプル点数（2 以上）
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率
            rotate: 回転角 [deg]（XY 平面、origin 回り）
            clip: True のとき矩形クリップ（AABB）で線を分割する
            clip_xmin: 変換後の座標でクリップ矩形の X 下限を指定します。, float, range [-200.0, 200.0]
            clip_xmax: 変換後の座標でクリップ矩形の X 上限を指定します。, float, range [-200.0, 200.0]
            clip_ymin: 変換後の座標でクリップ矩形の Y 下限を指定します。, float, range [-200.0, 200.0]
            clip_ymax: 変換後の座標でクリップ矩形の Y 上限を指定します。, float, range [-200.0, 200.0]
            a: 円柱一様流写像で障害物となる境界円の半径を指定します。, float, range [0.0, 50.0]
            U: 円柱一様流写像で W 座標を除算する流速スケールを指定します。, float, range [0.0, 5.0]
            gap: 格子線を境界円から離すため、半径に加える相対的な隙間を指定します。, float, range [0.0, 0.05]
            draw_boundary: `preset="cylinder_uniform"` で境界円を追加する
            boundary_samples: 境界円のサンプル数（3 以上）
            alpha_re: Möbius 写像 (αW+β)/(γW+δ) における α の実部を指定します。, float, range [-5.0, 5.0]
            alpha_im: Möbius 写像 (αW+β)/(γW+δ) における α の虚部を指定します。, float, range [-5.0, 5.0]
            beta_re: Möbius 写像 (αW+β)/(γW+δ) における β の実部を指定します。, float, range [-5.0, 5.0]
            beta_im: Möbius 写像 (αW+β)/(γW+δ) における β の虚部を指定します。, float, range [-5.0, 5.0]
            gamma_re: Möbius 写像 (αW+β)/(γW+δ) における γ の実部を指定します。, float, range [-5.0, 5.0]
            gamma_im: Möbius 写像 (αW+β)/(γW+δ) における γ の虚部を指定します。, float, range [-5.0, 5.0]
            delta_re: Möbius 写像 (αW+β)/(γW+δ) における δ の実部を指定します。, float, range [-5.0, 5.0]
            delta_im: Möbius 写像 (αW+β)/(γW+δ) における δ の虚部を指定します。, float, range [-5.0, 5.0]
            k_re: 指数写像 exp(kW) で W に掛ける複素係数 k の実部を指定します。, float, range [-5.0, 5.0]
            k_im: 指数写像 exp(kW) で W に掛ける複素係数 k の虚部を指定します。, float, range [-5.0, 5.0]
        """
        ...
    def line(self, *, activate: bool = ..., center: Vec3 = ..., anchor: Literal['center', 'left', 'right'] = ..., length: float = ..., angle: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        正規化済み引数から線分を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            center: `anchor` で指定した基準点の座標 (cx, cy, cz)
            anchor: `center` の基準点
            length: 線分の長さ
            angle: 回転角 [deg]
        """
        ...
    def lissajous(self, *, activate: bool = ..., a: int = ..., b: int = ..., phase: float = ..., samples: int = ..., turns: float = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        リサージュ曲線を 1 本の開ポリラインとして生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            a: X 方向の角周波数係数
            b: Y 方向の角周波数係数
            phase: X 方向の位相 [deg]
            samples: サンプリング点数
            turns: `t` 範囲の周回数
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...
    def lsystem(self, *, activate: bool = ..., kind: Literal['plant', 'circuit', 'custom'] = ..., iters: int = ..., center: Vec3 = ..., heading: float = ..., angle: float = ..., step: float = ..., jitter: float = ..., seed: int = ..., axiom: str = ..., rules: str = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        L-system を展開し、枝分かれした線（開ポリライン列）を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            kind: プリセット種別
            iters: 展開回数（0 で axiom をそのまま解釈する）
            center: 開始点の座標 (cx, cy, cz)
            heading: 初期向き [deg]
            angle: 回転角 [deg]（`+/-`）
            step: 前進距離（`F/f`）
            jitter: 角度/距離の相対ゆらぎ（0 以上）
            seed: 乱数 seed（決定性）
            axiom: 初期文字列（展開の出発点）
            rules: 置換規則（行ごとに `A=...` 形式）
        """
        ...
    def polygon(self, *, activate: bool = ..., n_sides: int = ..., phase: float = ..., sweep: float = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        正多角形の閉ポリラインを生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            n_sides: 辺の数
            phase: 頂点開始角 [deg]
            sweep: 描画する周回角 [deg]
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...
    def polyhedron(self, *, activate: bool = ..., kind: Literal['tetrahedron', 'hexahedron', 'octahedron', 'dodecahedron', 'icosahedron', 'cuboctahedron', 'icosidodecahedron', 'truncated_tetrahedron', 'truncated_cube', 'truncated_octahedron', 'truncated_dodecahedron', 'truncated_icosahedron', 'rhombicuboctahedron', 'snub_cube_left', 'snub_cube_right', 'snub_dodecahedron_left', 'snub_dodecahedron_right', 'truncated_cuboctahedron', 'rhombicosidodecahedron', 'truncated_icosidodecahedron'] = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        多面体を面ポリライン列として生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            kind: 多面体の名前
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...
    def polyline(self, *, activate: bool = ..., points: Sequence[Sequence[float]] = ..., closed: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        2D/3D point列から単一polylineを生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            closed: 終点が始点と異なる場合に始点を末尾へ追加して線を閉じます。, bool
        """
        ...
    def rect(self, *, activate: bool = ..., width: float = ..., height: float = ..., angle: float = ..., center: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        中心・幅・高さから閉じた長方形を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            width: 回転前の X 軸方向における長方形の幅を指定します。, float, range [0.0, 200.0]
            height: 回転前の Y 軸方向における長方形の高さを指定します。, float, range [0.0, 200.0]
            angle: 長方形を中心まわりに回転させる角度を度単位で指定します。, float, range [-180.0, 180.0]
            center: 長方形の中心となる XYZ 座標を指定します。, vec3, range [-300.0, 300.0]
        """
        ...
    def sphere(self, *, activate: bool = ..., subdivisions: int = ..., style: Literal['latlon', 'zigzag', 'icosphere', 'rings'] = ..., line_mode: Literal['horizontal', 'vertical', 'both'] = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        球のワイヤーフレームをポリライン列として生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            subdivisions: 細分化レベル（0..5 にクランプ）
            style: 生成方式
            line_mode: ``latlon`` / ``rings`` の線種
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...
    def text(self, *, activate: bool = ..., text: str = ..., font: str = ..., font_index: int = ..., text_align: Literal['left', 'center', 'right'] = ..., letter_spacing_em: float = ..., line_height: float = ..., use_bounding_box: bool = ..., box_width: float = ..., box_height: float = ..., show_bounding_box: bool = ..., quality: float = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        フォントアウトラインからテキストのポリライン列を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            text: 描画する文字列
            font: フォント指定（実在パス / ファイル名 / ステム / 部分一致）
            font_index: `.ttc` の subfont 番号（0 以上）
            text_align: 行揃え（`left|center|right`）
            letter_spacing_em: 文字間の追加スペーシング（em 比）
            line_height: 行送り（em 比）
            use_bounding_box: True のとき `box_width` による自動改行と、`show_bounding_box` による枠描画を有効にする
            box_width: 幅による自動改行を行う際のボックス幅（出力座標系）
            box_height: デバッグ用ボックス表示の高さ（出力座標系）
            show_bounding_box: True のとき、`box_width/box_height` で指定されたボックス枠（4本の線分）を追加で描画する
            quality: 平坦化品質（0..1）
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...
    def torus(self, *, activate: bool = ..., major_radius: float = ..., minor_radius: float = ..., major_segments: int = ..., minor_segments: int = ..., center: Vec3 = ..., scale: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> Geometry:
        """
        トーラスのワイヤーフレーム（子午線+緯線）を生成する。

        引数:
            activate: このプリミティブによる形状生成を有効にする。, bool
            major_radius: 大半径
            minor_radius: 小半径
            major_segments: major 方向の分割数
            minor_segments: minor 方向の分割数
            center: 平行移動ベクトル (cx, cy, cz)
            scale: 等方スケール倍率 s
        """
        ...

class _EffectBuilder(Protocol):
    def __call__(self, geometry: Geometry, *more_geometries: Geometry) -> Geometry:
        """保持している effect 列を Geometry に適用する。"""
        ...
    def affine(self, *, activate: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., rotation: Vec3 = ..., scale: Vec3 = ..., delta: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        スケール→回転→平行移動を適用する（合成アフィン変換）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            auto_center: True なら頂点の平均座標を中心に使用する
            pivot: `auto_center=False` のときの変換中心
            rotation: 各軸の回転角 [deg]（rx, ry, rz）
            scale: 各軸の倍率（sx, sy, sz）
            delta: 最後に適用する平行移動量 [mm]（dx, dy, dz）
        """
        ...
    def bold(self, *, activate: bool = ..., count: int = ..., radius: float = ..., seed: int = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        入力を複製して太線風にする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            count: 出力ストローク数（元の線を 1 本含む）
            radius: ずらし量の最大半径 [mm] 相当（XY のみ）
            seed: ずらし量生成の乱数シード（決定性のため）
        """
        ...
    def buffer(self, *, activate: bool = ..., join: Literal['mitre', 'round', 'bevel'] = ..., quad_segs: int = ..., distance: float = ..., union: bool = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        Shapely の buffer を用いて輪郭を生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            join: 角の処理
            quad_segs: 円弧近似分割数（Shapely の `quad_segs` 相当）
            distance: buffer 距離 [mm]
            union: True のとき、入力内の複数ポリラインを同一平面へ射影して統合し、 1回の buffer で重なりをまとめた輪郭を返す
            keep_original: True のとき buffer 結果に加えて元のポリラインも出力に含める
        """
        ...
    def clip(self, *, activate: bool = ..., mode: Literal['inside', 'outside'] = ..., draw_outline: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        XY 平面へ整列した上で、閉曲線マスクで線分列をクリップする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: `"inside"` はマスク内側だけ残す
            draw_outline: True のとき、マスク輪郭を追加で出力に含める
        """
        ...
    def collapse(self, *, activate: bool = ..., intensity: float = ..., subdivisions: int = ..., intensity_mask_base: Vec3 = ..., intensity_mask_slope: Vec3 = ..., auto_center: bool = ..., pivot: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        線分を細分化してノイズで崩す（非接続）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            intensity: 変位量（長さ単位は座標系に従う）
            subdivisions: 細分回数
            intensity_mask_base: ジオメトリ bbox の中心（正規化座標 t=0）における intensity 乗算係数（軸別）
            intensity_mask_slope: 正規化座標 t∈[-1,+1] に対する係数勾配（軸別）
            auto_center: True のとき `pivot` を無視し、入力 bbox の中心を pivot として扱う
            pivot: auto_center=False のときの pivot（ワールド座標）
        """
        ...
    def dash(self, *, activate: bool = ..., dash_length: float | Sequence[float] = ..., gap_length: float | Sequence[float] = ..., offset: float | Sequence[float] = ..., offset_jitter: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        連続線を破線に変換する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            dash_length: ダッシュ（描画区間）の長さ [mm]
            gap_length: ギャップ（非描画区間）の長さ [mm]
            offset: パターン位相オフセット [mm]
            offset_jitter: ポリラインごとに offset に加えるジッター量 [mm]
        """
        ...
    def displace(self, *, activate: bool = ..., amplitude: Vec3 = ..., spatial_freq: Vec3 = ..., amplitude_gradient: Vec3 = ..., frequency_gradient: Vec3 = ..., gradient_center_offset: Vec3 = ..., gradient_profile: Literal['linear', 'radial'] = ..., gradient_radius: Vec3 = ..., min_gradient_factor: float = ..., max_gradient_factor: float = ..., t: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        3D Perlin ノイズで頂点を変位する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            amplitude: 変位量 [mm]（各軸別）
            spatial_freq: 空間周波数（各軸別）
            amplitude_gradient: 振幅の軸方向グラデーション係数（各軸別）
            frequency_gradient: 周波数の軸方向グラデーション係数（各軸別）
            gradient_center_offset: 勾配計算の中心オフセット（bbox 正規化座標、各軸別）
            gradient_profile: 勾配の形状
            gradient_radius: `"radial"` の距離 `d` を作るための半径（bbox 正規化座標、各軸別）
            min_gradient_factor: 勾配適用時の最小係数（0.0–1.0）
            max_gradient_factor: 勾配適用時の最大係数（1.0–4.0）
            t: 時間オフセット（位相）
        """
        ...
    def drop(self, *, activate: bool = ..., interval: int = ..., index_offset: int = ..., min_length: float = ..., max_length: float = ..., probability_base: Vec3 = ..., probability_slope: Vec3 = ..., by: Literal['line', 'face'] = ..., seed: int = ..., keep_mode: Literal['drop', 'keep'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        線や面を条件で間引く。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            interval: 線インデックスに対する間引きステップ
            index_offset: interval 判定の開始オフセット
            min_length: この長さ以下の線を対象とする
            max_length: この長さ以上の線を対象とする
            probability_base: ジオメトリ bbox の中心（正規化座標 t=0）における drop 確率（軸別）
            probability_slope: 正規化座標 t∈[-1,+1] に対する確率勾配（軸別）
            by: 判定単位
            seed: probability_* 使用時の乱数シード
            keep_mode: "drop": 条件に一致した線を捨てる
        """
        ...
    def extrude(self, *, activate: bool = ..., delta: Vec3 = ..., scale: float = ..., subdivisions: int = ..., center_mode: Literal['origin', 'auto'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        指定方向に押し出し、複製線と側面エッジを生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            delta: 押し出し量（dx, dy, dz）[mm]（長さは 0–200 にクランプ）
            scale: 複製線に適用するスケール係数（0–3 にクランプ）
            subdivisions: 中点挿入の細分回数（0–8 にクランプ）
            center_mode: "auto" のとき複製線の重心中心でスケールし、それ以外は原点中心でスケールする
        """
        ...
    def fill(self, *, activate: bool = ..., angle_sets: int | Sequence[int] = ..., angle: float | Sequence[float] = ..., density: float | Sequence[float] = ..., spacing_gradient: float | Sequence[float] = ..., remove_boundary: bool | Sequence[bool] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉領域をハッチングで塗りつぶす。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            angle_sets: 方向本数（シーケンス指定時はグループごとにサイクル適用）
            angle: 基準角 [deg]（シーケンス指定時はグループごとにサイクル適用）
            density: 旧仕様の密度スケール（シーケンス指定時はグループごとにサイクル適用）
            spacing_gradient: スキャン方向に沿った線間隔勾配（シーケンス指定時はグループごとにサイクル適用）
            remove_boundary: True なら入力境界（入力ポリライン）を出力から除去する（シーケンス指定時はグループごとにサイクル適用）
        """
        ...
    def growth(self, *, activate: bool = ..., seed_count: int = ..., target_spacing: float = ..., boundary_avoid: float = ..., boundary_mode: Literal['slide', 'bounce'] = ..., iters: int = ..., seed: int = ..., show_mask: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        マスク内で差分成長を行い、襞のような閉曲線群を生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            seed_count: マスク内へ配置する seed（初期ループ）数
            target_spacing: 目標点間隔 [mm]
            boundary_avoid: 境界近傍で内側へ押し戻す強さ（0 で無効）
            boundary_mode: `"slide"` は境界で外向き成分を除去し、沿って流れる
            iters: 反復回数
            seed: 乱数 seed（seed 配置の再現性のため）
            show_mask: True のとき、出力に入力 mask を追加で含める
        """
        ...
    def highpass(self, *, activate: bool = ..., step: float = ..., sigma: float = ..., gain: float = ..., closed: Literal['auto', 'open', 'closed'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリライン列を highpass（高周波強調）する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 再サンプル間隔（弧長）
            sigma: 低域成分を作るガウス平滑半径（`sigma/step` が実効的なスケール）
            gain: 高周波強調係数
            closed: 境界条件
        """
        ...
    def isocontour(self, *, activate: bool = ..., spacing: float = ..., phase: float = ..., max_dist: float = ..., mode: Literal['inside', 'outside', 'both'] = ..., grid_pitch: float = ..., gamma: float = ..., level_step: int = ..., auto_close_threshold: float = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉曲線群から等高線（等値線）を複数レベル抽出して出力する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            spacing: レベル間隔
            phase: レベルの位相（`0` だと境界 `SDF=0` が含まれる）
            max_dist: 抽出範囲（`|SDF| <= max_dist`）
            mode: `"inside"` は内側のみ、`"outside"` は外側のみ、`"both"` は両側を抽出する
            grid_pitch: SDF 評価グリッドのピッチ
            gamma: 距離の非線形（`1.0` は線形）
            level_step: レベルの間引き
            auto_close_threshold: 閉曲線とみなす端点距離閾値
            keep_original: True のとき、生成結果に加えて元の入力も出力に含める
        """
        ...
    def lowpass(self, *, activate: bool = ..., step: float = ..., sigma: float = ..., closed: Literal['auto', 'open', 'closed'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリライン列を低域通過（ローパス）して滑らかにする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 再サンプル間隔（弧長）
            sigma: ガウス平滑半径
            closed: 境界条件
        """
        ...
    def metaball(self, *, activate: bool = ..., radius: float = ..., threshold: float = ..., grid_pitch: float = ..., auto_close_threshold: float = ..., output: Literal['exterior', 'both'] = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉曲線群をメタボール的に接続し、輪郭（外周＋穴）を生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            radius: 接続の届く距離（falloff 半径）[mm]
            threshold: 等値線レベル
            grid_pitch: 距離場を評価する 2D グリッドのピッチ [mm]
            auto_close_threshold: 端点距離がこの値以下なら閉曲線扱いとして自動で閉じる [mm]
            output: 出力輪郭の選択
            keep_original: True のとき、生成結果に加えて元のポリラインも出力に含める
        """
        ...
    def mirror(self, *, activate: bool = ..., n_mirror: int = ..., cx: float = ..., cy: float = ..., source_positive_x: bool = ..., source_positive_y: bool = ..., show_planes: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        XY 平面でのミラー複製を行う。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            n_mirror: 1: x=cx による半空間ミラー
            cx: 対称軸または放射対称中心の X 座標。, float, range [-100.0, 100.0]
            cy: 対称軸または放射対称中心の Y 座標。, float, range [-100.0, 100.0]
            source_positive_x: n_mirror=1/2 のときの x 側ソース選択
            source_positive_y: n_mirror=2 のときの y 側ソース選択
            show_planes: 対称面（または放射状境界）を可視化用ラインとして出力へ追加する
        """
        ...
    def mirror3d(self, *, activate: bool = ..., mode: Literal['azimuth', 'polyhedral'] = ..., n_azimuth: int = ..., center: Vec3 = ..., axis: Vec3 = ..., phi0: float = ..., mirror_equator: bool = ..., source_side: bool = ..., group: Literal['T', 'O', 'I'] = ..., use_reflection: bool = ..., show_planes: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        3D 放射状ミラー（azimuth / polyhedral）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: "azimuth" は回転軸を含む 2 平面でくさびを作り、回転と反射で複製する
            n_azimuth: "azimuth" の等分数
            center: 回転/反射の中心
            axis: "azimuth" の回転軸
            phi0: くさびの開始角 [deg]（"azimuth" のみ）
            mirror_equator: 赤道面（axis ⟂）でさらにミラーする（"azimuth" のみ）
            source_side: mirror_equator=True のときのソース側
            group: "polyhedral" の回転群（T=12, O=24, I=60）
            use_reflection: "polyhedral" で代表反射（y=0）を追加して倍化する
            show_planes: 対称面を可視化用の十字線として出力に追加する
        """
        ...
    def partition(self, *, activate: bool = ..., mode: Literal['merge', 'group', 'ring'] = ..., site_count: int = ..., seed: int = ..., site_density_base: Vec3 = ..., site_density_slope: Vec3 = ..., auto_center: bool = ..., pivot: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        偶奇規則の平面領域を Voronoi 分割し、閉ループ群を返す。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: 入力リングの扱い
            site_count: Voronoi のサイト数
            seed: 乱数シード（再現性）
            site_density_base: サイト密度（採用確率）の中心値（軸別）
            site_density_slope: 正規化座標 t∈[-1,+1] に対する密度勾配（軸別）
            auto_center: True のとき `pivot` を無視し、入力 bbox の中心を pivot として扱う
            pivot: auto_center=False のときの pivot（ワールド座標）
        """
        ...
    def pixelate(self, *, activate: bool = ..., step: Vec3 = ..., corner: Literal['auto', 'xy', 'yx'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリラインをグリッド上の階段線へ変換する（XY）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 各軸の格子間隔 (sx, sy, sz)
            corner: 対角（x と y が同時に動く）を 2 手へ分解するときの順序
        """
        ...
    def quantize(self, *, activate: bool = ..., step: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        頂点座標を各軸のステップ幅で量子化する（XYZ）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 各軸の格子間隔 (sx, sy, sz)
        """
        ...
    def reaction_diffusion(self, *, activate: bool = ..., grid_pitch: float = ..., steps: int = ..., du: float = ..., dv: float = ..., feed: float = ..., kill: float = ..., dt: float = ..., seed: int = ..., seed_radius: float = ..., noise: float = ..., level: float = ..., min_points: int = ..., boundary: Literal['noflux', 'dirichlet'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉曲線マスク内で反応拡散を走らせ、線として出力する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            grid_pitch: 計算グリッドのピッチ（出力座標系の長さ単位）
            steps: Gray-Scott の反復回数
            du: Gray-Scott モデルの U 成分に適用する拡散係数。, float, range [0.0, 1.0]
            dv: Gray-Scott モデルの V 成分に適用する拡散係数。, float, range [0.0, 1.0]
            feed: Gray-Scott モデルへ U 成分を供給する反応係数。, float, range [0.0, 0.1]
            kill: Gray-Scott モデルから V 成分を除去する反応係数。, float, range [0.0, 0.1]
            dt: 時間刻み
            seed: 乱数シード（初期条件用）
            seed_radius: 中心ブロブの半径（0 ならブロブ無し）
            noise: 初期ノイズ量（V に一様ノイズを加える）
            level: 等値線の閾値
            min_points: 出力するポリラインの最小点数
            boundary: マスク境界の扱い
        """
        ...
    def relax(self, *, activate: bool = ..., relaxation_iterations: int = ..., step: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        線分ネットワークをグラフとして弾性緩和する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            relaxation_iterations: 反復回数（0–50 にクランプ）
            step: 1 ステップの移動係数（0.0–0.5 にクランプ）
        """
        ...
    def repeat(self, *, activate: bool = ..., layout: Literal['grid', 'radial'] = ..., count: int = ..., radius: float = ..., theta: float = ..., n_theta: int = ..., n_radius: int = ..., cumulative_scale: bool = ..., cumulative_offset: bool = ..., cumulative_rotate: bool = ..., offset: Vec3 = ..., rotation_step: Vec3 = ..., scale: Vec3 = ..., curve: float = ..., auto_center: bool = ..., pivot: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        入力ジオメトリを複製して、規則的な配列を作る。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            layout: `"grid"` は `count/offset` による直交配置（現状維持）
            count: 複製回数
            radius: `layout="radial"` の外周半径 [mm]
            theta: `layout="radial"` の開始角 [deg]
            n_theta: `layout="radial"` の周方向配置数
            n_radius: `layout="radial"` の半径方向配置数
            cumulative_scale: True のときスケール補間にカーブ（t' = t**curve）を用いる
            cumulative_offset: True のときオフセット補間にカーブ（t' = t**curve）を用いる
            cumulative_rotate: True のとき回転補間にカーブ（t' = t**curve）を用いる
            offset: 終点オフセット [mm]
            rotation_step: 終点回転角 [deg]（rx, ry, rz）
            scale: 終点スケール倍率（sx, sy, sz）
            curve: カーブ係数
            auto_center: True なら平均座標を中心に使用
            pivot: `auto_center=False` のときの変換中心 [mm]
        """
        ...
    def rotate(self, *, activate: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., rotation: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        回転（auto_center / pivot 対応、degree 入力）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            auto_center: True なら頂点の平均座標を中心に使用
            pivot: 回転の中心（`auto_center=False` のとき有効）
            rotation: 各軸の回転角 [deg]（rx, ry, rz）
        """
        ...
    def scale(self, *, activate: bool = ..., mode: Literal['all', 'by_line', 'by_face'] = ..., auto_center: bool = ..., pivot: Vec3 = ..., scale: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        スケール変換を適用（auto_center 対応）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: `"all"` は入力全体を 1 つの中心でスケールする
            auto_center: True なら平均座標を中心に使用
            pivot: 変換の中心（`mode="all"` かつ `auto_center=False` のとき有効）
            scale: 各軸の倍率
        """
        ...
    def subdivide(self, *, activate: bool = ..., subdivisions: int = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        中点挿入で線を細分化する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            subdivisions: 細分回数
        """
        ...
    def translate(self, *, activate: bool = ..., delta: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        平行移動（XYZ のオフセット加算）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            delta: 平行移動量（dx, dy, dz）
        """
        ...
    def trim(self, *, activate: bool = ..., start_param: float = ..., end_param: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリライン列を正規化弧長の区間でトリムする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            start_param: 開始位置（0.0–1.0）
            end_param: 終了位置（0.0–1.0）
        """
        ...
    def twist(self, *, activate: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., angle: float = ..., axis_dir: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        位置に応じて軸回りにねじる（中心付近は 0）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            auto_center: True なら平均座標を回転中心に使用
            pivot: ねじり軸（`axis_dir` に平行な直線）の通過点（`auto_center=False` のとき有効）
            angle: 最大ねじれ角 [deg]
            axis_dir: ねじり軸方向（ベクトル）
        """
        ...
    def warp(self, *, activate: bool = ..., mode: Literal['lens', 'attract'] = ..., strength: float = ..., kind: Literal['scale', 'rotate', 'shear', 'swirl'] = ..., profile: Literal['band', 'ramp'] = ..., band: float = ..., inside_only: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., scale: float = ..., angle: float = ..., shear: Vec3 = ..., direction: Literal['attract', 'repel'] = ..., bias: float = ..., snap_band: float = ..., falloff: float = ..., show_mask: bool = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        マスク距離場で、入力線を lens/attract 変形する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: `"lens"` は座標変換をブレンドして歪ませる
            strength: 変形の強さ（0..2 を想定）
            kind: `mode="lens"` のときの座標変換種別
            profile: `mode="lens"` の距離プロファイル
            band: `mode="lens"` の距離スケール [mm]
            inside_only: `mode="lens"` で mask 内側だけに効かせるか
            auto_center: `mode="lens"` の中心を mask AABB center にする
            pivot: `auto_center=False` のときの中心
            scale: `kind="scale"` の倍率
            angle: `kind in {"rotate","swirl"}` の角度 [deg]
            shear: `kind="shear"` の shear 係数（x,y を使用）
            direction: `mode="attract"` の向き（吸着/反発）
            bias: `mode="attract"` の目標 signed distance [mm]（0 で境界）
            snap_band: `mode="attract"` で変形対象にする `|d-bias|` の上限（0 で無制限）
            falloff: `mode="attract"` の距離減衰スケール [mm]（0 でフラット）
            show_mask: True のとき、mask 入力も出力に含める（位置確認用）
            keep_original: True のとき、元の base も出力に含める（比較用）
        """
        ...
    def weave(self, *, activate: bool = ..., num_candidate_lines: int = ..., relaxation_iterations: int = ..., step: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        入力閉曲線からウェブ状の線分ネットワークを生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            num_candidate_lines: 候補線本数（0–500 にクランプ）
            relaxation_iterations: 弾性緩和の反復回数（0–50 にクランプ）
            step: 1 ステップの移動係数（0.0–0.5 にクランプ）
        """
        ...
    def wobble(self, *, activate: bool = ..., amplitude: Vec3 = ..., frequency: Vec3 = ..., phase: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        各頂点へサイン波由来の変位を加える。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            amplitude: 変位量 [mm] 相当（各軸別）
            frequency: 空間周波数（各軸別）
            phase: 位相 [deg]
        """
        ...

class _E(Protocol):
    def __call__(self, name: str | None = None) -> _E:
        """ラベル付き effect 名前空間を返す。"""
        ...
    def affine(self, *, activate: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., rotation: Vec3 = ..., scale: Vec3 = ..., delta: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        スケール→回転→平行移動を適用する（合成アフィン変換）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            auto_center: True なら頂点の平均座標を中心に使用する
            pivot: `auto_center=False` のときの変換中心
            rotation: 各軸の回転角 [deg]（rx, ry, rz）
            scale: 各軸の倍率（sx, sy, sz）
            delta: 最後に適用する平行移動量 [mm]（dx, dy, dz）
        """
        ...
    def bold(self, *, activate: bool = ..., count: int = ..., radius: float = ..., seed: int = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        入力を複製して太線風にする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            count: 出力ストローク数（元の線を 1 本含む）
            radius: ずらし量の最大半径 [mm] 相当（XY のみ）
            seed: ずらし量生成の乱数シード（決定性のため）
        """
        ...
    def buffer(self, *, activate: bool = ..., join: Literal['mitre', 'round', 'bevel'] = ..., quad_segs: int = ..., distance: float = ..., union: bool = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        Shapely の buffer を用いて輪郭を生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            join: 角の処理
            quad_segs: 円弧近似分割数（Shapely の `quad_segs` 相当）
            distance: buffer 距離 [mm]
            union: True のとき、入力内の複数ポリラインを同一平面へ射影して統合し、 1回の buffer で重なりをまとめた輪郭を返す
            keep_original: True のとき buffer 結果に加えて元のポリラインも出力に含める
        """
        ...
    def clip(self, *, activate: bool = ..., mode: Literal['inside', 'outside'] = ..., draw_outline: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        XY 平面へ整列した上で、閉曲線マスクで線分列をクリップする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: `"inside"` はマスク内側だけ残す
            draw_outline: True のとき、マスク輪郭を追加で出力に含める
        """
        ...
    def collapse(self, *, activate: bool = ..., intensity: float = ..., subdivisions: int = ..., intensity_mask_base: Vec3 = ..., intensity_mask_slope: Vec3 = ..., auto_center: bool = ..., pivot: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        線分を細分化してノイズで崩す（非接続）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            intensity: 変位量（長さ単位は座標系に従う）
            subdivisions: 細分回数
            intensity_mask_base: ジオメトリ bbox の中心（正規化座標 t=0）における intensity 乗算係数（軸別）
            intensity_mask_slope: 正規化座標 t∈[-1,+1] に対する係数勾配（軸別）
            auto_center: True のとき `pivot` を無視し、入力 bbox の中心を pivot として扱う
            pivot: auto_center=False のときの pivot（ワールド座標）
        """
        ...
    def dash(self, *, activate: bool = ..., dash_length: float | Sequence[float] = ..., gap_length: float | Sequence[float] = ..., offset: float | Sequence[float] = ..., offset_jitter: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        連続線を破線に変換する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            dash_length: ダッシュ（描画区間）の長さ [mm]
            gap_length: ギャップ（非描画区間）の長さ [mm]
            offset: パターン位相オフセット [mm]
            offset_jitter: ポリラインごとに offset に加えるジッター量 [mm]
        """
        ...
    def displace(self, *, activate: bool = ..., amplitude: Vec3 = ..., spatial_freq: Vec3 = ..., amplitude_gradient: Vec3 = ..., frequency_gradient: Vec3 = ..., gradient_center_offset: Vec3 = ..., gradient_profile: Literal['linear', 'radial'] = ..., gradient_radius: Vec3 = ..., min_gradient_factor: float = ..., max_gradient_factor: float = ..., t: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        3D Perlin ノイズで頂点を変位する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            amplitude: 変位量 [mm]（各軸別）
            spatial_freq: 空間周波数（各軸別）
            amplitude_gradient: 振幅の軸方向グラデーション係数（各軸別）
            frequency_gradient: 周波数の軸方向グラデーション係数（各軸別）
            gradient_center_offset: 勾配計算の中心オフセット（bbox 正規化座標、各軸別）
            gradient_profile: 勾配の形状
            gradient_radius: `"radial"` の距離 `d` を作るための半径（bbox 正規化座標、各軸別）
            min_gradient_factor: 勾配適用時の最小係数（0.0–1.0）
            max_gradient_factor: 勾配適用時の最大係数（1.0–4.0）
            t: 時間オフセット（位相）
        """
        ...
    def drop(self, *, activate: bool = ..., interval: int = ..., index_offset: int = ..., min_length: float = ..., max_length: float = ..., probability_base: Vec3 = ..., probability_slope: Vec3 = ..., by: Literal['line', 'face'] = ..., seed: int = ..., keep_mode: Literal['drop', 'keep'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        線や面を条件で間引く。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            interval: 線インデックスに対する間引きステップ
            index_offset: interval 判定の開始オフセット
            min_length: この長さ以下の線を対象とする
            max_length: この長さ以上の線を対象とする
            probability_base: ジオメトリ bbox の中心（正規化座標 t=0）における drop 確率（軸別）
            probability_slope: 正規化座標 t∈[-1,+1] に対する確率勾配（軸別）
            by: 判定単位
            seed: probability_* 使用時の乱数シード
            keep_mode: "drop": 条件に一致した線を捨てる
        """
        ...
    def extrude(self, *, activate: bool = ..., delta: Vec3 = ..., scale: float = ..., subdivisions: int = ..., center_mode: Literal['origin', 'auto'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        指定方向に押し出し、複製線と側面エッジを生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            delta: 押し出し量（dx, dy, dz）[mm]（長さは 0–200 にクランプ）
            scale: 複製線に適用するスケール係数（0–3 にクランプ）
            subdivisions: 中点挿入の細分回数（0–8 にクランプ）
            center_mode: "auto" のとき複製線の重心中心でスケールし、それ以外は原点中心でスケールする
        """
        ...
    def fill(self, *, activate: bool = ..., angle_sets: int | Sequence[int] = ..., angle: float | Sequence[float] = ..., density: float | Sequence[float] = ..., spacing_gradient: float | Sequence[float] = ..., remove_boundary: bool | Sequence[bool] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉領域をハッチングで塗りつぶす。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            angle_sets: 方向本数（シーケンス指定時はグループごとにサイクル適用）
            angle: 基準角 [deg]（シーケンス指定時はグループごとにサイクル適用）
            density: 旧仕様の密度スケール（シーケンス指定時はグループごとにサイクル適用）
            spacing_gradient: スキャン方向に沿った線間隔勾配（シーケンス指定時はグループごとにサイクル適用）
            remove_boundary: True なら入力境界（入力ポリライン）を出力から除去する（シーケンス指定時はグループごとにサイクル適用）
        """
        ...
    def growth(self, *, activate: bool = ..., seed_count: int = ..., target_spacing: float = ..., boundary_avoid: float = ..., boundary_mode: Literal['slide', 'bounce'] = ..., iters: int = ..., seed: int = ..., show_mask: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        マスク内で差分成長を行い、襞のような閉曲線群を生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            seed_count: マスク内へ配置する seed（初期ループ）数
            target_spacing: 目標点間隔 [mm]
            boundary_avoid: 境界近傍で内側へ押し戻す強さ（0 で無効）
            boundary_mode: `"slide"` は境界で外向き成分を除去し、沿って流れる
            iters: 反復回数
            seed: 乱数 seed（seed 配置の再現性のため）
            show_mask: True のとき、出力に入力 mask を追加で含める
        """
        ...
    def highpass(self, *, activate: bool = ..., step: float = ..., sigma: float = ..., gain: float = ..., closed: Literal['auto', 'open', 'closed'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリライン列を highpass（高周波強調）する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 再サンプル間隔（弧長）
            sigma: 低域成分を作るガウス平滑半径（`sigma/step` が実効的なスケール）
            gain: 高周波強調係数
            closed: 境界条件
        """
        ...
    def isocontour(self, *, activate: bool = ..., spacing: float = ..., phase: float = ..., max_dist: float = ..., mode: Literal['inside', 'outside', 'both'] = ..., grid_pitch: float = ..., gamma: float = ..., level_step: int = ..., auto_close_threshold: float = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉曲線群から等高線（等値線）を複数レベル抽出して出力する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            spacing: レベル間隔
            phase: レベルの位相（`0` だと境界 `SDF=0` が含まれる）
            max_dist: 抽出範囲（`|SDF| <= max_dist`）
            mode: `"inside"` は内側のみ、`"outside"` は外側のみ、`"both"` は両側を抽出する
            grid_pitch: SDF 評価グリッドのピッチ
            gamma: 距離の非線形（`1.0` は線形）
            level_step: レベルの間引き
            auto_close_threshold: 閉曲線とみなす端点距離閾値
            keep_original: True のとき、生成結果に加えて元の入力も出力に含める
        """
        ...
    def lowpass(self, *, activate: bool = ..., step: float = ..., sigma: float = ..., closed: Literal['auto', 'open', 'closed'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリライン列を低域通過（ローパス）して滑らかにする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 再サンプル間隔（弧長）
            sigma: ガウス平滑半径
            closed: 境界条件
        """
        ...
    def metaball(self, *, activate: bool = ..., radius: float = ..., threshold: float = ..., grid_pitch: float = ..., auto_close_threshold: float = ..., output: Literal['exterior', 'both'] = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉曲線群をメタボール的に接続し、輪郭（外周＋穴）を生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            radius: 接続の届く距離（falloff 半径）[mm]
            threshold: 等値線レベル
            grid_pitch: 距離場を評価する 2D グリッドのピッチ [mm]
            auto_close_threshold: 端点距離がこの値以下なら閉曲線扱いとして自動で閉じる [mm]
            output: 出力輪郭の選択
            keep_original: True のとき、生成結果に加えて元のポリラインも出力に含める
        """
        ...
    def mirror(self, *, activate: bool = ..., n_mirror: int = ..., cx: float = ..., cy: float = ..., source_positive_x: bool = ..., source_positive_y: bool = ..., show_planes: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        XY 平面でのミラー複製を行う。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            n_mirror: 1: x=cx による半空間ミラー
            cx: 対称軸または放射対称中心の X 座標。, float, range [-100.0, 100.0]
            cy: 対称軸または放射対称中心の Y 座標。, float, range [-100.0, 100.0]
            source_positive_x: n_mirror=1/2 のときの x 側ソース選択
            source_positive_y: n_mirror=2 のときの y 側ソース選択
            show_planes: 対称面（または放射状境界）を可視化用ラインとして出力へ追加する
        """
        ...
    def mirror3d(self, *, activate: bool = ..., mode: Literal['azimuth', 'polyhedral'] = ..., n_azimuth: int = ..., center: Vec3 = ..., axis: Vec3 = ..., phi0: float = ..., mirror_equator: bool = ..., source_side: bool = ..., group: Literal['T', 'O', 'I'] = ..., use_reflection: bool = ..., show_planes: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        3D 放射状ミラー（azimuth / polyhedral）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: "azimuth" は回転軸を含む 2 平面でくさびを作り、回転と反射で複製する
            n_azimuth: "azimuth" の等分数
            center: 回転/反射の中心
            axis: "azimuth" の回転軸
            phi0: くさびの開始角 [deg]（"azimuth" のみ）
            mirror_equator: 赤道面（axis ⟂）でさらにミラーする（"azimuth" のみ）
            source_side: mirror_equator=True のときのソース側
            group: "polyhedral" の回転群（T=12, O=24, I=60）
            use_reflection: "polyhedral" で代表反射（y=0）を追加して倍化する
            show_planes: 対称面を可視化用の十字線として出力に追加する
        """
        ...
    def partition(self, *, activate: bool = ..., mode: Literal['merge', 'group', 'ring'] = ..., site_count: int = ..., seed: int = ..., site_density_base: Vec3 = ..., site_density_slope: Vec3 = ..., auto_center: bool = ..., pivot: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        偶奇規則の平面領域を Voronoi 分割し、閉ループ群を返す。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: 入力リングの扱い
            site_count: Voronoi のサイト数
            seed: 乱数シード（再現性）
            site_density_base: サイト密度（採用確率）の中心値（軸別）
            site_density_slope: 正規化座標 t∈[-1,+1] に対する密度勾配（軸別）
            auto_center: True のとき `pivot` を無視し、入力 bbox の中心を pivot として扱う
            pivot: auto_center=False のときの pivot（ワールド座標）
        """
        ...
    def pixelate(self, *, activate: bool = ..., step: Vec3 = ..., corner: Literal['auto', 'xy', 'yx'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリラインをグリッド上の階段線へ変換する（XY）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 各軸の格子間隔 (sx, sy, sz)
            corner: 対角（x と y が同時に動く）を 2 手へ分解するときの順序
        """
        ...
    def quantize(self, *, activate: bool = ..., step: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        頂点座標を各軸のステップ幅で量子化する（XYZ）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            step: 各軸の格子間隔 (sx, sy, sz)
        """
        ...
    def reaction_diffusion(self, *, activate: bool = ..., grid_pitch: float = ..., steps: int = ..., du: float = ..., dv: float = ..., feed: float = ..., kill: float = ..., dt: float = ..., seed: int = ..., seed_radius: float = ..., noise: float = ..., level: float = ..., min_points: int = ..., boundary: Literal['noflux', 'dirichlet'] = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        閉曲線マスク内で反応拡散を走らせ、線として出力する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            grid_pitch: 計算グリッドのピッチ（出力座標系の長さ単位）
            steps: Gray-Scott の反復回数
            du: Gray-Scott モデルの U 成分に適用する拡散係数。, float, range [0.0, 1.0]
            dv: Gray-Scott モデルの V 成分に適用する拡散係数。, float, range [0.0, 1.0]
            feed: Gray-Scott モデルへ U 成分を供給する反応係数。, float, range [0.0, 0.1]
            kill: Gray-Scott モデルから V 成分を除去する反応係数。, float, range [0.0, 0.1]
            dt: 時間刻み
            seed: 乱数シード（初期条件用）
            seed_radius: 中心ブロブの半径（0 ならブロブ無し）
            noise: 初期ノイズ量（V に一様ノイズを加える）
            level: 等値線の閾値
            min_points: 出力するポリラインの最小点数
            boundary: マスク境界の扱い
        """
        ...
    def relax(self, *, activate: bool = ..., relaxation_iterations: int = ..., step: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        線分ネットワークをグラフとして弾性緩和する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            relaxation_iterations: 反復回数（0–50 にクランプ）
            step: 1 ステップの移動係数（0.0–0.5 にクランプ）
        """
        ...
    def repeat(self, *, activate: bool = ..., layout: Literal['grid', 'radial'] = ..., count: int = ..., radius: float = ..., theta: float = ..., n_theta: int = ..., n_radius: int = ..., cumulative_scale: bool = ..., cumulative_offset: bool = ..., cumulative_rotate: bool = ..., offset: Vec3 = ..., rotation_step: Vec3 = ..., scale: Vec3 = ..., curve: float = ..., auto_center: bool = ..., pivot: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        入力ジオメトリを複製して、規則的な配列を作る。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            layout: `"grid"` は `count/offset` による直交配置（現状維持）
            count: 複製回数
            radius: `layout="radial"` の外周半径 [mm]
            theta: `layout="radial"` の開始角 [deg]
            n_theta: `layout="radial"` の周方向配置数
            n_radius: `layout="radial"` の半径方向配置数
            cumulative_scale: True のときスケール補間にカーブ（t' = t**curve）を用いる
            cumulative_offset: True のときオフセット補間にカーブ（t' = t**curve）を用いる
            cumulative_rotate: True のとき回転補間にカーブ（t' = t**curve）を用いる
            offset: 終点オフセット [mm]
            rotation_step: 終点回転角 [deg]（rx, ry, rz）
            scale: 終点スケール倍率（sx, sy, sz）
            curve: カーブ係数
            auto_center: True なら平均座標を中心に使用
            pivot: `auto_center=False` のときの変換中心 [mm]
        """
        ...
    def rotate(self, *, activate: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., rotation: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        回転（auto_center / pivot 対応、degree 入力）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            auto_center: True なら頂点の平均座標を中心に使用
            pivot: 回転の中心（`auto_center=False` のとき有効）
            rotation: 各軸の回転角 [deg]（rx, ry, rz）
        """
        ...
    def scale(self, *, activate: bool = ..., mode: Literal['all', 'by_line', 'by_face'] = ..., auto_center: bool = ..., pivot: Vec3 = ..., scale: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        スケール変換を適用（auto_center 対応）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: `"all"` は入力全体を 1 つの中心でスケールする
            auto_center: True なら平均座標を中心に使用
            pivot: 変換の中心（`mode="all"` かつ `auto_center=False` のとき有効）
            scale: 各軸の倍率
        """
        ...
    def subdivide(self, *, activate: bool = ..., subdivisions: int = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        中点挿入で線を細分化する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            subdivisions: 細分回数
        """
        ...
    def translate(self, *, activate: bool = ..., delta: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        平行移動（XYZ のオフセット加算）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            delta: 平行移動量（dx, dy, dz）
        """
        ...
    def trim(self, *, activate: bool = ..., start_param: float = ..., end_param: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        ポリライン列を正規化弧長の区間でトリムする。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            start_param: 開始位置（0.0–1.0）
            end_param: 終了位置（0.0–1.0）
        """
        ...
    def twist(self, *, activate: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., angle: float = ..., axis_dir: Vec3 = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        位置に応じて軸回りにねじる（中心付近は 0）。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            auto_center: True なら平均座標を回転中心に使用
            pivot: ねじり軸（`axis_dir` に平行な直線）の通過点（`auto_center=False` のとき有効）
            angle: 最大ねじれ角 [deg]
            axis_dir: ねじり軸方向（ベクトル）
        """
        ...
    def warp(self, *, activate: bool = ..., mode: Literal['lens', 'attract'] = ..., strength: float = ..., kind: Literal['scale', 'rotate', 'shear', 'swirl'] = ..., profile: Literal['band', 'ramp'] = ..., band: float = ..., inside_only: bool = ..., auto_center: bool = ..., pivot: Vec3 = ..., scale: float = ..., angle: float = ..., shear: Vec3 = ..., direction: Literal['attract', 'repel'] = ..., bias: float = ..., snap_band: float = ..., falloff: float = ..., show_mask: bool = ..., keep_original: bool = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        マスク距離場で、入力線を lens/attract 変形する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            mode: `"lens"` は座標変換をブレンドして歪ませる
            strength: 変形の強さ（0..2 を想定）
            kind: `mode="lens"` のときの座標変換種別
            profile: `mode="lens"` の距離プロファイル
            band: `mode="lens"` の距離スケール [mm]
            inside_only: `mode="lens"` で mask 内側だけに効かせるか
            auto_center: `mode="lens"` の中心を mask AABB center にする
            pivot: `auto_center=False` のときの中心
            scale: `kind="scale"` の倍率
            angle: `kind in {"rotate","swirl"}` の角度 [deg]
            shear: `kind="shear"` の shear 係数（x,y を使用）
            direction: `mode="attract"` の向き（吸着/反発）
            bias: `mode="attract"` の目標 signed distance [mm]（0 で境界）
            snap_band: `mode="attract"` で変形対象にする `|d-bias|` の上限（0 で無制限）
            falloff: `mode="attract"` の距離減衰スケール [mm]（0 でフラット）
            show_mask: True のとき、mask 入力も出力に含める（位置確認用）
            keep_original: True のとき、元の base も出力に含める（比較用）
        """
        ...
    def weave(self, *, activate: bool = ..., num_candidate_lines: int = ..., relaxation_iterations: int = ..., step: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        入力閉曲線からウェブ状の線分ネットワークを生成する。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            num_candidate_lines: 候補線本数（0–500 にクランプ）
            relaxation_iterations: 弾性緩和の反復回数（0–50 にクランプ）
            step: 1 ステップの移動係数（0.0–0.5 にクランプ）
        """
        ...
    def wobble(self, *, activate: bool = ..., amplitude: Vec3 = ..., frequency: Vec3 = ..., phase: float = ..., key: str | int | None = ..., instance_key: str | int | None = ..., shared: bool = ...) -> _EffectBuilder:
        """
        各頂点へサイン波由来の変位を加える。

        引数:
            activate: このエフェクトによる形状変換を有効にする。, bool
            amplitude: 変位量 [mm] 相当（各軸別）
            frequency: 空間周波数（各軸別）
            phase: 位相 [deg]
        """
        ...

class _L(Protocol):
    def __call__(
        self,
        name: str | None = None,
    ) -> _L:
        """ラベル付き Layer 名前空間を返す。"""
        ...

    def layer(
        self,
        geometry_or_list: Geometry | Sequence[Geometry],
        *,
        key: str | int | None = ...,
        instance_key: str | int | None = ...,
        shared: bool = ...,
        color: Vec3 | None = ...,
        thickness: float | None = ...,
    ) -> Layer:
        """単体/複数の Geometry を単一 Layer にする。"""
        ...

class _P(Protocol):
    def __call__(
        self,
        name: str | None = None,
        *,
        key: str | int | None = None,
        instance_key: str | int | None = None,
        shared: bool = False,
    ) -> _P:
        """ラベル付き preset 名前空間を返す。"""
        ...

    def __getattr__(self, name: str) -> Callable[..., SceneItem]:
        """preset を `P.<name>(...)` で呼び出す。"""
        ...

G: _G
E: _E
L: _L

P: _P

from grafix.api.export import export as export
from grafix.api.render import (Color as Color, ExportFormat as ExportFormat, ExportResult as ExportResult, Frame as Frame, RenderOptions as RenderOptions, RenderSession as RenderSession, RenderSessionMetadata as RenderSessionMetadata, render as render)
from grafix.api.variation_batch import (VariationBatchResult as VariationBatchResult, VariationRenderResult as VariationRenderResult, render_variation_batch as render_variation_batch)
from grafix.api.preset import preset as preset
from grafix.core.effect_registry import effect as effect
from grafix.core.primitive_registry import primitive as primitive
from grafix.core.resource_budget import ResourceBudget as ResourceBudget, ResourceLimitError as ResourceLimitError

from grafix.core.runtime_limits import (RuntimeLimitProfiles as RuntimeLimitProfiles, RuntimeLimits as RuntimeLimits)

def run(
    draw: Callable[[float], SceneItem],
    *,
    config_path: str | Path | None = ...,
    run_id: str | None = ...,
    background_color: Vec3 = ...,
    line_thickness: float = ...,
    line_color: Vec3 = ...,
    render_scale: float = ...,
    canvas_size: tuple[int, int] = ...,
    parameter_gui: bool = ...,
    parameter_persistence: bool = ...,
    midi_port_name: str | None = ...,
    midi_mode: str = ...,
    n_worker: int = ...,
    evaluation_timeout: float | None = ...,
    fps: float = ...,
    seed: int | None = ...,
    resource_budget: ResourceBudget = ...,
    runtime_limit_profiles: RuntimeLimitProfiles | None = ...,
) -> None:
    """`draw(t)` を既定の background 1 worker で評価し、リアルタイム描画する。

    `n_worker=0` の場合だけ同期評価し、`>=1` は background worker 数を表す。
    """
    ...

__all__ = ['Color', 'E', 'ExportFormat', 'ExportResult', 'Frame', 'G', 'L', 'P', 'RenderOptions', 'RenderSession', 'RenderSessionMetadata', 'ResourceBudget', 'ResourceLimitError', 'RuntimeLimitProfiles', 'RuntimeLimits', 'VariationBatchResult', 'VariationRenderResult', 'effect', 'export', 'preset', 'primitive', 'render', 'render_variation_batch', 'run']
